<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TRs</name>
   <tag></tag>
   <elementGuidId>1283bcb4-d421-4d41-89d1-bbd0f04ee493</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[@class=&quot;container&quot;]/table/tbody/tr[1]/td/div/div[8]/div/table/tbody/tr</value>
   </webElementProperties>
</WebElementEntity>
